### ISSUE TITLE
Frequency and Magnitude are called before they are defined in the Matlab version.  

### ISSUE THREAD

**Issue by Vishnu-RISE-ETC** [szkafander/lattice_fringe#1]
I think Line 72 , which is: 
[freq, unc, magn] = fb.get_frequencies(im.resize(scale), 'mode', 'strongest_vote'); should be defined before sub-plotting frequency and magnitude.

![Matlab Issue](https://user-images.githubusercontent.com/79299587/119342877-f87ca780-bc95-11eb-9200-1921efce3eb2.JPG)

**Comment by szkafander** [comment]
Thanks, that is correct. I've noticed this a while ago but did not have time to correct. If you'd like, feel free to submit a PR, otherwise I'll fix it in a few days.

**Comment by szkafander** [comment]
Fixed.
